# Generated by Django 3.2.18 on 2023-04-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'Diaries'},
        ),
        migrations.AlterModelOptions(
            name='therapy',
            options={'verbose_name_plural': 'Therapies'},
        ),
    ]
